const BRANCHES = {
  COMPUTER_SCIENCE: 'COMPUTER_SCIENCE',
  ELECTRONICS: 'ELECTRONICS',
  MECHANICAL: 'MECHANICAL',
  CIVIL: 'CIVIL',
  ELECTRICAL: 'ELECTRICAL',
};

const BRANCH_LABELS = {
  [BRANCHES.COMPUTER_SCIENCE]: 'Computer Science',
  [BRANCHES.ELECTRONICS]: 'Electronics',
  [BRANCHES.MECHANICAL]: 'Mechanical',
  [BRANCHES.CIVIL]: 'Civil',
  [BRANCHES.ELECTRICAL]: 'Electrical',
};

const BRANCH_VALUES = Object.values(BRANCHES);

module.exports = { BRANCHES, BRANCH_LABELS, BRANCH_VALUES };
