const INTERVIEW_TYPES = {
  TECHNICAL: 'TECHNICAL',
  HR: 'HR',
  APTITUDE: 'APTITUDE',
  RESUME: 'RESUME',
};

const INTERVIEW_TYPE_LABELS = {
  [INTERVIEW_TYPES.TECHNICAL]: 'Technical',
  [INTERVIEW_TYPES.HR]: 'HR',
  [INTERVIEW_TYPES.APTITUDE]: 'Aptitude',
  [INTERVIEW_TYPES.RESUME]: 'Resume',
};

const INTERVIEW_TYPE_VALUES = Object.values(INTERVIEW_TYPES);

const BRANCH_REQUIRED_TYPES = [INTERVIEW_TYPES.TECHNICAL];

const RESUME_SUPPORTED_TYPES = [INTERVIEW_TYPES.RESUME];

module.exports = {
  INTERVIEW_TYPES,
  INTERVIEW_TYPE_LABELS,
  INTERVIEW_TYPE_VALUES,
  BRANCH_REQUIRED_TYPES,
  RESUME_SUPPORTED_TYPES,
};
