const SESSION_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED',
  EXPIRED: 'EXPIRED',
};

const SESSION_STATUS_VALUES = Object.values(SESSION_STATUS);

module.exports = { SESSION_STATUS, SESSION_STATUS_VALUES };
