const { BRANCHES } = require('../../constants/branches');
const { INTERVIEW_TYPES } = require('../../constants/interviewTypes');
const { DIFFICULTY } = require('../../constants/difficulty');

const localQuestions = {
  [BRANCHES.COMPUTER_SCIENCE]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'How would you explain what a computer program is to someone non-technical?', difficulty: DIFFICULTY.EASY },
      { content: 'Can you walk me through the difference between hardware and software?', difficulty: DIFFICULTY.EASY },
      { content: 'How does an operating system work, in simple terms?', difficulty: DIFFICULTY.EASY },
      { content: 'What does an operating system actually do for you?', difficulty: DIFFICULTY.EASY },
      { content: 'Can you explain what a process is in the context of an OS?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you explain a thread to someone who has never heard the term?', difficulty: DIFFICULTY.EASY },
      { content: 'When would you choose multithreading over a single thread?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What happens when two threads try to access the same resource at the same time?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain what a deadlock is and how you would prevent it?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What conditions need to be true for a deadlock to occur?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does virtual memory work when your RAM runs out?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain paging and why an OS uses it?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a file system organize data on a disk?', difficulty: DIFFICULTY.EASY },
      { content: 'What makes a compiler different from an interpreter?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you pick a compiler over an interpreter?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you explain what an algorithm is?', difficulty: DIFFICULTY.EASY },
      { content: 'What makes one algorithm better than another?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain Big O notation and why it matters?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you use a linked list instead of an array?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain the difference between a stack and a queue with a real example?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you use a stack in a real application?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a binary search tree help with searching?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the practical difference between BFS and DFS?', difficulty: DIFFICULTY.HARD },
      { content: 'How do you think about recursion when solving a problem?', difficulty: DIFFICULTY.EASY },
      { content: 'When would recursion be a better choice than iteration?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What sorting algorithm would you reach for and why?', difficulty: DIFFICULTY.EASY },
      { content: 'How does binary search work and when would you use it?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would merge sort be a better choice than bubble sort?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain hashing in a way that connects to something you have used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What happens when two keys hash to the same index?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you explain object-oriented programming to a peer?', difficulty: DIFFICULTY.EASY },
      { content: 'Can you walk me through the main ideas behind OOP?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you decide when to use inheritance versus composition?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you give me a simple example of polymorphism in Java?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you use an interface over an abstract class?', difficulty: DIFFICULTY.HARD },
      { content: 'How does a constructor work and when would you write a custom one?', difficulty: DIFFICULTY.EASY },
      { content: 'What is encapsulation and why does it matter in practice?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you think about designing a database for a new application?', difficulty: DIFFICULTY.EASY },
      { content: 'When would you pick a relational database over NoSQL?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do primary keys and foreign keys work together?', difficulty: DIFFICULTY.EASY },
      { content: 'Can you explain the difference between DELETE, DROP, and TRUNCATE?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you use a LEFT JOIN versus an INNER JOIN?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why would you normalize a database, and when might you not?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain what ACID properties mean in practice?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you use an index to speed up a slow query?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a NoSQL database and when would you reach for one?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does DNS actually work when you type a URL?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between TCP and UDP and when would you use each?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain how HTTP and HTTPS differ?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you explain a REST API to someone who has never built one?', difficulty: DIFFICULTY.EASY },
      { content: 'When would you use POST instead of GET?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does client-server architecture work in a web app?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you walk me through how you have used Git in a project?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between Git and GitHub?', difficulty: DIFFICULTY.EASY },
      { content: 'How do you handle merge conflicts in Git?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What testing approach do you usually follow?', difficulty: DIFFICULTY.EASY },
      { content: 'When would you write a unit test versus an integration test?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you usually debug a problem you cannot immediately figure out?', difficulty: DIFFICULTY.EASY },
      { content: 'Can you explain the difference between authentication and authorization?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a session work in a web application?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a JWT and when would you use one?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you explain cloud computing to a non-technical friend?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a virtual machine and a container?', difficulty: DIFFICULTY.HARD },
      { content: 'Why do people use Docker in development?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does Agile change the way a team works compared to Waterfall?', difficulty: DIFFICULTY.MEDIUM },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  [BRANCHES.ELECTRONICS]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'How would you explain what electronics is about?', difficulty: DIFFICULTY.EASY },
      { content: 'Can you explain the difference between analog and digital signals?', difficulty: DIFFICULTY.EASY },
      { content: 'How does voltage, current, and resistance relate to each other?', difficulty: DIFFICULTY.EASY },
      { content: 'Can you explain Ohm\'s law and when you have applied it?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between AC and DC and where do you see each?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you explain a series circuit versus a parallel circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'When would you use a capacitor versus an inductor in a circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does impedance differ from resistance and when does it matter?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain how a diode works and what it is used for?', difficulty: DIFFICULTY.EASY },
      { content: 'When would you use a Zener diode instead of a regular diode?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a rectifier convert AC to DC?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain how a transistor works as a switch?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the practical difference between a BJT and a MOSFET?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you use a transistor as an amplifier?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an op-amp and when would you use one?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does negative feedback help in an electronic circuit?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an oscillator and where do you find one in everyday devices?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a voltage regulator work and why do you need one?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a linear and switching power supply?', difficulty: DIFFICULTY.HARD },
      { content: 'How do sensors and actuators work together in a system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain what an embedded system is with a real example?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you pick a microcontroller over a microprocessor?', difficulty: DIFFICULTY.HARD },
      { content: 'How do logic gates work together to build a digital circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'Why are NAND and NOR gates called universal gates?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the practical difference between a combinational and sequential circuit?', difficulty: DIFFICULTY.HARD },
      { content: 'How does a flip-flop store a single bit of information?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you use a multiplexer in a digital design?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does an ADC convert an analog signal to digital?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the Nyquist sampling theorem and why does it matter?', difficulty: DIFFICULTY.HARD },
      { content: 'Can you explain the difference between AM and FM in simple terms?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does optical fiber communication work?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you choose Bluetooth over Wi-Fi for a project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a PCB help in building electronic circuits?', difficulty: DIFFICULTY.EASY },
      { content: 'Can you explain what soldering involves and why it is important?', difficulty: DIFFICULTY.EASY },
      { content: 'How does doping change the behavior of a semiconductor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a PN junction and how does it work?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do integrated circuits compare to discrete component circuits?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is a clock signal important in a digital system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What makes a real-time embedded system different from a regular one?', difficulty: DIFFICULTY.HARD },
      { content: 'How do communication protocols like UART, SPI, and I2C differ?', difficulty: DIFFICULTY.HARD },
      { content: 'What is the difference between hardware and firmware?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you explain IoT to someone who has never heard of it?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between Arduino and Raspberry Pi?', difficulty: DIFFICULTY.HARD },
      { content: 'Have you worked on an embedded project? What was your role?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you troubleshoot an electronic circuit that is not working?', difficulty: DIFFICULTY.HARD },
      { content: 'What safety precautions do you follow when working with circuits?', difficulty: DIFFICULTY.MEDIUM },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  [BRANCHES.MECHANICAL]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'How would you explain what mechanical engineering is about?', difficulty: DIFFICULTY.EASY },
      { content: 'Can you walk me through how force, work, and power relate to each other?', difficulty: DIFFICULTY.EASY },
      { content: 'How do you explain torque to someone who has never heard the term?', difficulty: DIFFICULTY.EASY },
      { content: 'When does stress versus strain become an important consideration?', difficulty: DIFFICULTY.EASY },
      { content: 'How does Young\'s modulus help you understand a material?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What makes a material ductile versus brittle and why does it matter?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you decide on a factor of safety for a design?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between conduction, convection, and radiation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain the second law of thermodynamics in simple terms?', difficulty: DIFFICULTY.HARD },
      { content: 'How does an internal combustion engine actually work?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the practical difference between petrol and diesel engines?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you walk me through the four strokes of a four-stroke engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a two-stroke engine differ from a four-stroke and when would you use each?', difficulty: DIFFICULTY.HARD },
      { content: 'Why is lubrication so critical in an engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a cooling system keep an engine running properly?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a pump, a compressor, and a turbine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does Bernoulli\'s principle apply in a real system?', difficulty: DIFFICULTY.HARD },
      { content: 'When would you choose a hydraulic system over a pneumatic one?', difficulty: DIFFICULTY.HARD },
      { content: 'How do gears work together to transfer motion and force?', difficulty: DIFFICULTY.EASY },
      { content: 'When would you use a spur gear versus a helical gear?', difficulty: DIFFICULTY.HARD },
      { content: 'How do bearings help a machine function properly?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a clutch and a brake?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you choose a belt drive over a chain drive?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does welding differ from soldering and when would you use each?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between casting, forging, and machining?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does CNC machining compare to conventional machining?', difficulty: DIFFICULTY.HARD },
      { content: 'When would you use a lathe versus a milling machine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How is 3D printing being used in mechanical engineering today?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is quality control important in manufacturing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you think about tolerance when designing a part?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Can you explain the difference between CAD and CAM?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you use finite element analysis in a design project?', difficulty: DIFFICULTY.HARD },
      { content: 'What role does a flywheel play in an engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a refrigeration system actually cool things down?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between preventive and predictive maintenance?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you troubleshoot a machine that suddenly stops working?', difficulty: DIFFICULTY.HARD },
      { content: 'How are robots changing manufacturing today?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is mechatronics and how does it connect to mechanical engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Have you worked on a mechanical engineering project? What was your role?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you approach designing a simple mechanical component?', difficulty: DIFFICULTY.HARD },
      { content: 'How do you choose the right material for a machine part?', difficulty: DIFFICULTY.HARD },
      { content: 'What safety precautions do you follow when working with machines?', difficulty: DIFFICULTY.MEDIUM },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  [BRANCHES.CIVIL]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'How would you explain what civil engineering is about?', difficulty: DIFFICULTY.EASY },
      { content: 'What loads does a building need to handle and why does that matter?', difficulty: DIFFICULTY.EASY },
      { content: 'How do stress and strain relate to each other in a structure?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What makes a material ductile versus brittle in construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you decide on a factor of safety for a building?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What goes into a concrete mix and why does the ratio matter?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is curing important for concrete?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does reinforced concrete work and why is steel used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When would you use prestressed concrete instead of regular RCC?', difficulty: DIFFICULTY.HARD },
      { content: 'What is the difference between a beam, a column, and a slab?', difficulty: DIFFICULTY.EASY },
      { content: 'When would you choose a deep foundation over a shallow one?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a retaining wall work?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a load-bearing structure and a framed structure?', difficulty: DIFFICULTY.HARD },
      { content: 'How does brick masonry differ from block masonry?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is waterproofing important in building construction?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you prevent dampness in a building?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What happens during a site investigation and why is it important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How is surveying used in civil engineering?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between surveying and leveling?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you assess the bearing capacity of soil?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What causes soil settlement and why is it a concern?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between flexible and rigid pavement?', difficulty: DIFFICULTY.HARD },
      { content: 'How does road drainage help protect a highway?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a bridge and a culvert?', difficulty: DIFFICULTY.HARD },
      { content: 'How does wastewater treatment work?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between water supply and drainage engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does BIM help in civil engineering projects?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What makes green building different from conventional construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you approach estimating costs for a construction project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is project scheduling critical in construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you inspect a concrete structure for damage?', difficulty: DIFFICULTY.HARD },
      { content: 'What would you check if a building develops cracks?', difficulty: DIFFICULTY.HARD },
      { content: 'Have you worked on a civil engineering project? What was your role?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you choose a suitable foundation for a building?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you improve safety at a construction site?', difficulty: DIFFICULTY.HARD },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  [BRANCHES.ELECTRICAL]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'How would you explain what electrical engineering is about?', difficulty: DIFFICULTY.EASY },
      { content: 'How do voltage, current, and resistance relate in a circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between AC and DC power?', difficulty: DIFFICULTY.EASY },
      { content: 'When would you use a series circuit versus a parallel circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do resistors, capacitors, and inductors each affect a circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What makes a transformer work and where is it used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why does a transformer work with AC and not ordinary DC?', difficulty: DIFFICULTY.HARD },
      { content: 'How does an electric motor convert electrical energy to motion?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a synchronous and induction motor?', difficulty: DIFFICULTY.HARD },
      { content: 'How does electromagnetic induction work in practice?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between single-phase and three-phase power?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a generator produce electricity?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is power factor and why does it matter?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a circuit breaker protect an electrical system?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a fuse and a circuit breaker?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does earthing protect people and equipment?', difficulty: DIFFICULTY.EASY },
      { content: 'What causes a short circuit and how do you prevent it?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a solar panel generate electricity?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What makes a smart grid different from a traditional power grid?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do conductors, insulators, and semiconductors differ in behavior?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a diode control the direction of current?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a transistor used for in an electrical circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a logic gate form the basis of digital circuits?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between an analog and digital signal?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a microcontroller interact with sensors and actuators?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What communication protocols have you used in embedded projects?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a PCB help in building electronic circuits?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you use a multimeter to diagnose a circuit problem?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How does a variable frequency drive control motor speed?', difficulty: DIFFICULTY.HARD },
      { content: 'What is the difference between star and delta connections?', difficulty: DIFFICULTY.HARD },
      { content: 'Have you worked on an electrical engineering project? What was your role?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you troubleshoot a basic electrical circuit that is not working?', difficulty: DIFFICULTY.HARD },
      { content: 'What would you check first if an electrical motor suddenly stopped working?', difficulty: DIFFICULTY.HARD },
      { content: 'What safety precautions do you follow when working with electrical equipment?', difficulty: DIFFICULTY.MEDIUM },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  GLOBAL: {
    [INTERVIEW_TYPES.HR]: [
      { content: 'Tell me about yourself.', difficulty: DIFFICULTY.EASY },
      { content: 'Can you briefly introduce yourself?', difficulty: DIFFICULTY.EASY },
      { content: 'Tell me about your educational background.', difficulty: DIFFICULTY.EASY },
      { content: 'Why did you choose your current field of study?', difficulty: DIFFICULTY.EASY },
      { content: 'What made you interested in your field?', difficulty: DIFFICULTY.EASY },
      { content: 'What do you enjoy most about your studies?', difficulty: DIFFICULTY.EASY },
      { content: 'What are some skills you have developed during your studies?', difficulty: DIFFICULTY.EASY },
      { content: 'What are your main strengths?', difficulty: DIFFICULTY.EASY },
      { content: 'What is one weakness you are currently trying to improve?', difficulty: DIFFICULTY.EASY },
      { content: 'What is one achievement you are proud of?', difficulty: DIFFICULTY.EASY },
      { content: 'What are you most proud of about yourself?', difficulty: DIFFICULTY.EASY },
      { content: 'What motivates you to do your best?', difficulty: DIFFICULTY.EASY },
      { content: 'What are your career goals?', difficulty: DIFFICULTY.EASY },
      { content: 'Where do you see yourself in the next three to five years?', difficulty: DIFFICULTY.EASY },
      { content: 'Why did you choose this field as a career?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why did you choose to apply for this role? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What interests you about this role? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why do you think you are suitable for this role? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What skills do you think are important for this role? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Which skill are you currently trying to improve for your future career?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you hope to learn from your first job?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What made you interested in working in this field?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why would you like to start your career at a company? [Assume a suitable company in your field.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are you looking for in your first job?', difficulty: DIFFICULTY.EASY },
      { content: 'What do you expect from your first workplace?', difficulty: DIFFICULTY.EASY },
      { content: 'What would make you excited to come to work every day?', difficulty: DIFFICULTY.EASY },
      { content: 'What made you apply for this opportunity? [Assume a suitable entry-level job opportunity.]', difficulty: DIFFICULTY.EASY },
      { content: 'Why should a company consider hiring you as a fresher?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you think you can contribute as a student or fresher?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What attracts you to this kind of job? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you think would be important to learn when starting a new job? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you prepare yourself before starting a new job? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you think would be the biggest challenge when starting your first job?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would you want to learn during your first few weeks at work? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why would you choose this career path instead of a different one? [Assume a suitable career related to your field of study.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a project you worked on during your studies. [Assume a simple academic project if you do not have a specific project in mind.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about something you learned from a project during your studies. [Assume a simple academic project if needed.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a challenge you faced while working on something during your studies. [Assume a simple academic task or project.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about something you recently learned on your own.', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you usually learn something that you do not understand?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time when you had to learn something quickly.', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you do when you get stuck while working on something?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you manage multiple assignments or deadlines?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you had to work under pressure.', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you balance your studies with other responsibilities?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you worked with other people on a task. [Assume a college assignment or group activity.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you think makes someone a good team member?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Do you prefer working alone or working in a team? Why?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you handle a disagreement with a teammate? [Assume a college or workplace team.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if a teammate was not completing their part of the work? [Assume a college or workplace team.]', difficulty: DIFFICULTY.HARD },
      { content: 'How would you communicate with someone who had a different opinion from yours?', difficulty: DIFFICULTY.HARD },
      { content: 'Tell me about a time you helped someone with their work. [Assume a college assignment or group activity.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time someone helped you with a difficult task. [Assume a college assignment or group activity.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you explain a difficult idea to someone who does not understand the topic?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you make sure your ideas are clearly understood by others?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you handle criticism?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you respond when someone points out a mistake in your work?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you received feedback and used it to improve. [Assume a college or academic situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a mistake you made and what you learned from it. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a difficult situation you faced and how you handled it. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you failed at something and what you learned from it. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you had to adapt to a change. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you had to make an important decision. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would you do if you were given a task you had never done before? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were given a difficult task with a short deadline? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were given instructions that you did not completely understand? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were asked to learn something you had never used before? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you discovered a mistake in your work just before a deadline? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if two teammates disagreed about how to solve a problem? [Assume a typical workplace team.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if your manager gave you a deadline that seemed difficult to meet? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if your first attempt at a task did not work? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were not confident about completing an assigned task? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'How would you ask for help when you need it? [Assume a suitable workplace.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would you do if you did not know the answer to a question during an interview?', difficulty: DIFFICULTY.HARD },
      { content: 'How do you prioritize your tasks when you have several things to do?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you make sure you complete your work on time?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you do when you lose motivation while working?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you handle stressful situations?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How comfortable are you with asking for help?', difficulty: DIFFICULTY.EASY },
      { content: 'How do you react when plans suddenly change?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How comfortable are you with working with people you have never met before?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you handle working with someone who has a very different working style from yours? [Assume a typical workplace.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you received feedback that you disagreed with? [Assume a workplace situation.]', difficulty: DIFFICULTY.HARD },
      { content: 'How would you respond if your manager asked you to improve an area where you thought you were already doing well? [Assume a workplace situation.]', difficulty: DIFFICULTY.HARD },
      { content: 'What kind of work environment helps you perform your best? [Assume a typical workplace.]', difficulty: DIFFICULTY.EASY },
      { content: 'What kind of manager do you think helps employees perform well? [Assume a typical workplace.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would you expect from your manager when starting a new job? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What does professionalism mean to you?', difficulty: DIFFICULTY.EASY },
      { content: 'What does success mean to you?', difficulty: DIFFICULTY.EASY },
      { content: 'How would your classmates describe you?', difficulty: DIFFICULTY.EASY },
      { content: 'What is one quality that makes you different from others?', difficulty: DIFFICULTY.EASY },
      { content: 'What is something about yourself that you would like to improve?', difficulty: DIFFICULTY.EASY },
      { content: 'What is one habit that has helped you become better at something?', difficulty: DIFFICULTY.EASY },
      { content: 'What is something you struggled with but eventually improved?', difficulty: DIFFICULTY.EASY },
      { content: 'What gives you confidence when facing a new challenge?', difficulty: DIFFICULTY.EASY },
      { content: 'What do you do when you feel nervous before an important event?', difficulty: DIFFICULTY.EASY },
      { content: 'What do you think will be the biggest challenge when moving from college to a workplace?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are you hoping to gain from your first professional experience?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you think your education has prepared you for a workplace?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is one thing you wish you had learned earlier?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you react if your first assignment was different from what you expected? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were asked to learn something completely new during your first month at work? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were given a task without much guidance? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'How would you build good relationships with your teammates? [Assume a typical workplace.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would make you feel that your first job was a successful experience?', difficulty: DIFFICULTY.EASY },
    ],
    [INTERVIEW_TYPES.APTITUDE]: [
      { content: 'What is 20% of 250?', difficulty: DIFFICULTY.EASY },
      { content: 'If a number is increased by 20% and becomes 240, what was the original number?', difficulty: DIFFICULTY.EASY },
      { content: 'A product costs ₹500 and is sold for ₹600. What is the profit percentage?', difficulty: DIFFICULTY.EASY },
      { content: 'A product is bought for ₹800 and sold for ₹720. What is the loss percentage?', difficulty: DIFFICULTY.EASY },
      { content: 'If the price of an item increases from ₹400 to ₹480, what is the percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'If a number is decreased by 25% and becomes 150, what was the original number?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the average of 10, 20, 30, 40, and 50?', difficulty: DIFFICULTY.EASY },
      { content: 'The average of five numbers is 24. What is their total?', difficulty: DIFFICULTY.EASY },
      { content: 'The average age of four people is 25 years. What is their total age?', difficulty: DIFFICULTY.EASY },
      { content: 'The average of three numbers is 30. If two of the numbers are 20 and 40, what is the third number?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'The ratio of two numbers is 2:3 and their sum is 50. What are the two numbers?', difficulty: DIFFICULTY.EASY },
      { content: 'The ratio of boys to girls in a class is 3:2. If there are 30 boys, how many girls are there?', difficulty: DIFFICULTY.EASY },
      { content: 'If 5 pens cost ₹100, how much would 8 pens cost at the same rate?', difficulty: DIFFICULTY.EASY },
      { content: 'A person earns ₹30,000 per month and saves ₹6,000. What percentage of their income do they save?', difficulty: DIFFICULTY.EASY },
      { content: 'If 40% of a number is 80, what is the number?', difficulty: DIFFICULTY.EASY },
      { content: 'What is 15% of 360?', difficulty: DIFFICULTY.EASY },
      { content: 'A number is increased from 200 to 250. What is the percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'A number is reduced from 500 to 400. What is the percentage decrease?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between simple interest and compound interest?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the simple interest on ₹5,000 at 10% per year for 2 years?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the amount after applying 10% simple interest to ₹2,000 for 3 years?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If ₹10,000 is invested at 10% compound interest per year, what will be the amount after one year?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the formula for simple interest?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the formula for calculating profit percentage?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the formula for calculating loss percentage?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the formula for calculating percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'A train travels 120 km in 2 hours. What is its average speed?', difficulty: DIFFICULTY.EASY },
      { content: 'A car travels at 60 km/h for 3 hours. What distance does it cover?', difficulty: DIFFICULTY.EASY },
      { content: 'How much time does it take to travel 150 km at a speed of 50 km/h?', difficulty: DIFFICULTY.EASY },
      { content: 'A person walks at 5 km/h. How long will it take to walk 15 km?', difficulty: DIFFICULTY.EASY },
      { content: 'Two cars travel at speeds of 40 km/h and 60 km/h. Which car covers more distance in 2 hours and by how much?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between speed and velocity?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A train travels 300 km at an average speed of 75 km/h. How long does the journey take?', difficulty: DIFFICULTY.EASY },
      { content: 'If a person\'s speed increases from 40 km/h to 50 km/h, what is the percentage increase in speed?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A man completes a journey in 5 hours at 40 km/h. How far does he travel?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the basic formula relating distance, speed, and time?', difficulty: DIFFICULTY.EASY },
      { content: 'If one person can complete a task in 10 days, what fraction of the work can they complete in one day?', difficulty: DIFFICULTY.EASY },
      { content: 'If one person can complete a job in 10 days and another can complete it in 20 days, how long will they take together?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A can complete a task in 12 days and B can complete it in 18 days. How long will they take working together?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 5 workers complete a job in 12 days, how many worker-days are required?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 10 workers can complete a task in 6 days, how many days would 5 workers need at the same rate?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A pipe can fill a tank in 4 hours. What fraction of the tank does it fill in one hour?', difficulty: DIFFICULTY.EASY },
      { content: 'One pipe fills a tank in 6 hours and another fills it in 3 hours. How long will they take together?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If a person completes half of a task in 5 days, how many days would they need to complete the whole task at the same rate?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between work and rate of work?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of getting a head when a fair coin is tossed?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of getting a 6 when a fair die is rolled?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of getting an even number on a fair die?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of drawing a red card from a standard deck of cards?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of getting two heads when a fair coin is tossed twice?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A bag contains 3 red balls and 2 blue balls. What is the probability of picking a red ball?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between probability and possibility?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the probability of an event that is certain to happen?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of an impossible event?', difficulty: DIFFICULTY.EASY },
      { content: 'If a coin is tossed three times, how many possible outcomes are there?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the next number in the sequence 2, 4, 6, 8, 10?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the next number in the sequence 3, 6, 12, 24?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the next number in the sequence 1, 4, 9, 16, 25?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the missing number in the sequence 5, 10, 15, 20, __?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the missing number in the sequence 2, 6, 12, 20, __?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the next number in the sequence 1, 1, 2, 3, 5, 8?', difficulty: DIFFICULTY.EASY },
      { content: 'If A is taller than B and B is taller than C, who is the shortest?', difficulty: DIFFICULTY.EASY },
      { content: 'If all roses are flowers and some flowers are red, can we conclude that all roses are red?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A clock shows 3:00. What is the angle between the hour and minute hands?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How many degrees are there in a full circle?', difficulty: DIFFICULTY.EASY },
      { content: 'How many minutes are there in 2.5 hours?', difficulty: DIFFICULTY.EASY },
      { content: 'If today is Monday, what day will it be after 10 days?', difficulty: DIFFICULTY.EASY },
      { content: 'How many days are there in two weeks?', difficulty: DIFFICULTY.EASY },
      { content: 'If a shirt is discounted by 20% from ₹1,000, what is the final price?', difficulty: DIFFICULTY.EASY },
      { content: 'A shop offers two successive discounts of 10% and 20%. Is the total discount 30%?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'An item costs ₹1,000 after a 20% discount. What was its original price?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A salary increases from ₹25,000 to ₹30,000. What is the percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'If your monthly expenses are ₹18,000 and your income is ₹30,000, what percentage of your income is spent?', difficulty: DIFFICULTY.EASY },
      { content: 'A student scores 72 out of 100 in an exam. What percentage did the student score?', difficulty: DIFFICULTY.EASY },
      { content: 'A student scores 80 marks in one test and 90 marks in another. What is the average score?', difficulty: DIFFICULTY.EASY },
      { content: 'If 60% of a class of 50 students are present, how many students are present?', difficulty: DIFFICULTY.EASY },
      { content: 'A company has 200 employees and 25% work remotely. How many employees work remotely?', difficulty: DIFFICULTY.EASY },
      { content: 'If 30% of a number is 45, what is 70% of the same number?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A number is divided in the ratio 4:5. If the smaller part is 20, what is the larger part?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'The ratio of two numbers is 5:7 and their difference is 18. What are the numbers?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 4 notebooks cost ₹120, what is the cost of 10 notebooks?', difficulty: DIFFICULTY.EASY },
      { content: 'If 12 workers produce 240 units in a day, how many units would 6 workers produce at the same rate?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A machine produces 100 units in 5 hours. How many units does it produce per hour?', difficulty: DIFFICULTY.EASY },
      { content: 'A company produced 800 units last month and 1,000 units this month. What is the percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'A student spends 2 hours studying, 1 hour exercising, and 3 hours on other activities each day. What percentage of the 6 hours is spent studying?', difficulty: DIFFICULTY.EASY },
      { content: 'A person travels 40 km in the first hour and 60 km in the second hour. What is the average speed for the two-hour journey?', difficulty: DIFFICULTY.EASY },
      { content: 'A car travels half of a journey at 40 km/h and the other half at 60 km/h. Is the average speed 50 km/h?', difficulty: DIFFICULTY.HARD },
      { content: 'A person buys an item for ₹500 and wants a 20% profit. At what price should it be sold?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A product has a marked price of ₹2,000 and is sold for ₹1,600. What percentage discount was given?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 3 machines produce 900 units in 5 hours, how many units can one machine produce in 5 hours at the same rate?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A tank contains 100 liters of water. If 20 liters are removed, what percentage of the water remains?', difficulty: DIFFICULTY.EASY },
      { content: 'A class has 40 students. If 5 students are absent, what percentage of students are present?', difficulty: DIFFICULTY.EASY },
      { content: 'If a number is multiplied by 5 and then increased by 10, the result is 60. What is the number?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 3x = 27, what is the value of x?', difficulty: DIFFICULTY.EASY },
      { content: 'If x + 15 = 40, what is the value of x?', difficulty: DIFFICULTY.EASY },
      { content: 'If 2x + 5 = 25, what is the value of x?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the smallest positive number divisible by both 4 and 6?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the greatest common factor of 12 and 18?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the least common multiple of 6 and 8?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a prime number and a composite number?', difficulty: DIFFICULTY.EASY },
      { content: 'Is 29 a prime number? Why?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the remainder when 25 is divided by 4?', difficulty: DIFFICULTY.EASY },
      { content: 'A number is divisible by both 3 and 5. What can you say about the number?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the square of 15?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the square root of 144?', difficulty: DIFFICULTY.EASY },
      { content: 'What is 2 to the power of 5?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the value of 10 divided by 0.5?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between an odd number and an even number?', difficulty: DIFFICULTY.EASY },
      { content: 'If five consecutive integers have an average of 20, what is the middle number?', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
};

module.exports = localQuestions;
