const { BRANCHES } = require('../../constants/branches');
const { INTERVIEW_TYPES } = require('../../constants/interviewTypes');
const { DIFFICULTY } = require('../../constants/difficulty');

const localQuestions = {
  [BRANCHES.COMPUTER_SCIENCE]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'What is a computer program?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between hardware and software?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an operating system?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main functions of an operating system?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a process?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a thread?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a process and a thread?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is multitasking in an operating system?', difficulty: DIFFICULTY.EASY },
      { content: 'What is multithreading?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a deadlock in an operating system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are the basic conditions required for a deadlock?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is virtual memory?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is paging in an operating system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a file system?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a file and a directory?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a compiler?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an interpreter?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a compiler and an interpreter?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an algorithm?', difficulty: DIFFICULTY.EASY },
      { content: 'What makes an algorithm efficient?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between time complexity and space complexity?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Big O notation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an array?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between an array and a linked list?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a linked list?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a stack?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a queue?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a stack and a queue?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a circular queue?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a binary tree?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a binary search tree?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a binary tree and a binary search tree?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a graph in computer science?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between BFS and DFS?', difficulty: DIFFICULTY.HARD },
      { content: 'What is recursion?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the advantages and disadvantages of recursion?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is sorting?', difficulty: DIFFICULTY.EASY },
      { content: 'What is searching?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between linear search and binary search?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is binary search?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between merge sort and bubble sort?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is hashing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a hash table?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a collision in hashing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is object-oriented programming?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main concepts of object-oriented programming?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a class?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an object?', difficulty: DIFFICULTY.EASY },
      { content: 'What is encapsulation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is inheritance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is polymorphism?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is abstraction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a class and an object?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between method overloading and method overriding?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a constructor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of a constructor in object-oriented programming?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an interface?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between an abstract class and an interface?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a database?', difficulty: DIFFICULTY.EASY },
      { content: 'Why are databases used?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a relational database?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a table in a relational database?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a primary key?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a foreign key?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a primary key and a foreign key?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is SQL?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between DELETE, DROP, and TRUNCATE in SQL?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a JOIN in SQL?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between INNER JOIN and LEFT JOIN?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is normalization in a database?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is normalization used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a transaction in a database?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are ACID properties?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an index in a database?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a NoSQL database?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between SQL and NoSQL databases?', difficulty: DIFFICULTY.HARD },
      { content: 'What is computer networking?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an IP address?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between IPv4 and IPv6?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a MAC address?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a router?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a switch in networking?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a router and a switch?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is DNS?', difficulty: DIFFICULTY.EASY },
      { content: 'What is HTTP?', difficulty: DIFFICULTY.EASY },
      { content: 'What is HTTPS?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between HTTP and HTTPS?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a web server?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an API?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a REST API?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between GET and POST requests?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is JSON?', difficulty: DIFFICULTY.EASY },
      { content: 'What is client-server architecture?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Git?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is Git used in software development?', difficulty: DIFFICULTY.EASY },
      { content: 'What is GitHub?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between Git and GitHub?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a branch in Git?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a merge in Git?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is version control?', difficulty: DIFFICULTY.EASY },
      { content: 'What is software testing?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between unit testing and integration testing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is debugging?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a bug in software?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the software development life cycle?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Agile methodology?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between frontend and backend development?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an API endpoint?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is authentication?', difficulty: DIFFICULTY.EASY },
      { content: 'What is authorization?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between authentication and authorization?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a session in web applications?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a cookie?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a JWT?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a cookie and local storage?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is cloud computing?', difficulty: DIFFICULTY.EASY },
      { content: 'What is virtualization?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a virtual machine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Docker?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is Docker used in software development?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a virtual machine and a container?', difficulty: DIFFICULTY.HARD },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  [BRANCHES.ELECTRONICS]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'What is electronics?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between analog and digital signals?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an analog signal?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a digital signal?', difficulty: DIFFICULTY.EASY },
      { content: 'What is voltage?', difficulty: DIFFICULTY.EASY },
      { content: 'What is current?', difficulty: DIFFICULTY.EASY },
      { content: 'What is resistance?', difficulty: DIFFICULTY.EASY },
      { content: 'What is power in an electrical circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'What is Ohm\'s law?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between AC and DC?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a series circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a parallel circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a resistor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of a resistor in a circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a capacitor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of a capacitor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an inductor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of an inductor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is impedance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between resistance and impedance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a diode?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the main purpose of a diode?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a Zener diode?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an LED?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a photodiode?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a rectifier?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between half-wave and full-wave rectifiers?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a transistor?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main types of transistors?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a BJT?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between NPN and PNP transistors?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a MOSFET?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a BJT and a MOSFET?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a transistor used for?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a transistor as a switch?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a transistor as an amplifier?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an amplifier?', difficulty: DIFFICULTY.EASY },
      { content: 'What is gain in an amplifier?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an operational amplifier?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an op-amp used for?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a comparator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is feedback in an electronic circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between positive and negative feedback?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an oscillator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the purpose of an oscillator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a voltage regulator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is a voltage regulator used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a power supply?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a linear power supply?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a switching power supply?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a sensor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an actuator?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a sensor and an actuator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an embedded system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are the main parts of an embedded system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a microcontroller?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a microprocessor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a microcontroller and a microprocessor?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a microcontroller used for?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a digital circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a logic gate?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the basic logic gates?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an AND gate?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an OR gate?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a NOT gate?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a NAND gate?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a NOR gate?', difficulty: DIFFICULTY.EASY },
      { content: 'Why are NAND and NOR called universal gates?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an XOR gate?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a truth table?', difficulty: DIFFICULTY.EASY },
      { content: 'What is Boolean algebra?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a combinational circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a sequential circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between combinational and sequential circuits?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a flip-flop?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a register?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a counter?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a multiplexer?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a demultiplexer?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an encoder?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a decoder?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an ADC?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a DAC?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is an ADC used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is a DAC used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is sampling in digital communication?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the Nyquist sampling theorem?', difficulty: DIFFICULTY.HARD },
      { content: 'What is modulation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is modulation needed in communication systems?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is amplitude modulation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is frequency modulation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is phase modulation?', difficulty: DIFFICULTY.HARD },
      { content: 'What is the difference between AM and FM?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a transmitter?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a receiver?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an antenna?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of an antenna?', difficulty: DIFFICULTY.EASY },
      { content: 'What is bandwidth?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is noise in a communication system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is signal-to-noise ratio?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a communication channel?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is wireless communication?', difficulty: DIFFICULTY.EASY },
      { content: 'What is optical fiber communication?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are the advantages of optical fiber communication?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Bluetooth?', difficulty: DIFFICULTY.EASY },
      { content: 'What is Wi-Fi?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between Bluetooth and Wi-Fi?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is GPS?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a PCB?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is a PCB used?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the basic parts of a PCB?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is soldering?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of soldering?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a semiconductor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a conductor, semiconductor, and insulator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is silicon and why is it commonly used in electronics?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is doping in semiconductors?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a P-type semiconductor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an N-type semiconductor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a PN junction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is VLSI?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an integrated circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the advantage of using integrated circuits?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is CMOS?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a clock signal?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is a clock signal important in digital systems?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a real-time embedded system?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an interrupt in a microcontroller?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is PWM?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Where is PWM commonly used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is UART?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is SPI?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is I2C?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between UART, SPI, and I2C?', difficulty: DIFFICULTY.HARD },
      { content: 'What is GPIO?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a sensor interface in an embedded system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between hardware and firmware?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is firmware?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a bootloader?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is IoT?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an IoT device?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the basic components of an IoT system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do sensors communicate with a microcontroller?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a development board?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of a development board?', difficulty: DIFFICULTY.EASY },
      { content: 'What is Arduino?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between Arduino and a microcontroller?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Raspberry Pi?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a microcontroller and Raspberry Pi?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an embedded project you have worked on?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What was your role in your electronics project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What was the most difficult part of your electronics project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What did you learn from your electronics project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you troubleshoot an electronic circuit that is not working?', difficulty: DIFFICULTY.HARD },
      { content: 'What would you check first if a circuit suddenly stopped working?', difficulty: DIFFICULTY.HARD },
      { content: 'What safety precautions should be followed while working with electronic circuits?', difficulty: DIFFICULTY.MEDIUM },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  [BRANCHES.MECHANICAL]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'What is mechanical engineering?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main areas of mechanical engineering?', difficulty: DIFFICULTY.EASY },
      { content: 'What is force?', difficulty: DIFFICULTY.EASY },
      { content: 'What is work?', difficulty: DIFFICULTY.EASY },
      { content: 'What is power?', difficulty: DIFFICULTY.EASY },
      { content: 'What is energy?', difficulty: DIFFICULTY.EASY },
      { content: 'What is torque?', difficulty: DIFFICULTY.EASY },
      { content: 'What is pressure?', difficulty: DIFFICULTY.EASY },
      { content: 'What is density?', difficulty: DIFFICULTY.EASY },
      { content: 'What is stress?', difficulty: DIFFICULTY.EASY },
      { content: 'What is strain?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between stress and strain?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is elasticity?', difficulty: DIFFICULTY.EASY },
      { content: 'What is plasticity?', difficulty: DIFFICULTY.EASY },
      { content: 'What is Young\'s modulus?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a factor of safety?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a material property?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a ductile and brittle material?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is hardness?', difficulty: DIFFICULTY.EASY },
      { content: 'What is toughness?', difficulty: DIFFICULTY.EASY },
      { content: 'What is fatigue in materials?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is creep?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is friction?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main types of friction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is friction important in mechanical systems?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is lubrication?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is lubrication used in machines?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is heat?', difficulty: DIFFICULTY.EASY },
      { content: 'What is temperature?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between heat and temperature?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is heat transfer?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the three modes of heat transfer?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is conduction?', difficulty: DIFFICULTY.EASY },
      { content: 'What is convection?', difficulty: DIFFICULTY.EASY },
      { content: 'What is radiation?', difficulty: DIFFICULTY.EASY },
      { content: 'What is thermal conductivity?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is thermodynamics?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the basic laws of thermodynamics?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the first law of thermodynamics?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the second law of thermodynamics?', difficulty: DIFFICULTY.HARD },
      { content: 'What is entropy?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an engine?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between an engine and a motor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an internal combustion engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between petrol and diesel engines?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a four-stroke engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are the four strokes of a four-stroke engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a two-stroke engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between two-stroke and four-stroke engines?', difficulty: DIFFICULTY.HARD },
      { content: 'What is engine efficiency?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a cooling system in an engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is lubrication important in an engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a pump?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a compressor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a pump and a compressor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a turbine?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a pump and a turbine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is fluid mechanics?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a fluid?', difficulty: DIFFICULTY.EASY },
      { content: 'What is viscosity?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is pressure in a fluid?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Bernoulli\'s principle?', difficulty: DIFFICULTY.HARD },
      { content: 'What is Pascal\'s law?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is buoyancy?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a hydraulic system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a pneumatic system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between hydraulic and pneumatic systems?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a machine?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a mechanism?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a machine and a mechanism?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a gear?', difficulty: DIFFICULTY.EASY },
      { content: 'Why are gears used in machines?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a spur gear and a helical gear?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a gear ratio?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a bearing?', difficulty: DIFFICULTY.EASY },
      { content: 'Why are bearings used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a ball bearing and a roller bearing?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a shaft?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a coupling?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a clutch?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a brake?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a clutch and a brake?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a belt drive?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a chain drive?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between belt drive and chain drive?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is welding?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is welding used in manufacturing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are the common types of welding?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is arc welding?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is gas welding?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is soldering?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between welding and soldering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is casting?', difficulty: DIFFICULTY.EASY },
      { content: 'What is forging?', difficulty: DIFFICULTY.EASY },
      { content: 'What is machining?', difficulty: DIFFICULTY.EASY },
      { content: 'What is turning in machining?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is milling?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is drilling?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between turning and milling?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a lathe machine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is CNC machining?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between CNC and conventional machining?', difficulty: DIFFICULTY.HARD },
      { content: 'What is 3D printing?', difficulty: DIFFICULTY.EASY },
      { content: 'How is 3D printing used in mechanical engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is manufacturing?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between manufacturing and machining?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is quality control?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is quality important in manufacturing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is tolerance in manufacturing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is surface finish?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a fitting?', difficulty: DIFFICULTY.EASY },
      { content: 'What is metrology?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is measurement accuracy?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is measurement precision?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a vernier caliper?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a micrometer?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a vernier caliper and a micrometer?', difficulty: DIFFICULTY.HARD },
      { content: 'What is CAD?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is CAD used in mechanical engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is CAM?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between CAD and CAM?', difficulty: DIFFICULTY.HARD },
      { content: 'What is CAE?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is finite element analysis?', difficulty: DIFFICULTY.HARD },
      { content: 'What is simulation in mechanical engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a technical drawing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an engineering drawing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is dimensioning in engineering drawings?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an assembly drawing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a machine component?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a shaft used for?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a spring?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a spring used for?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a flywheel?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the purpose of a flywheel?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a governor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the purpose of a governor in an engine?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a heat exchanger?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a refrigeration system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is air conditioning?', difficulty: DIFFICULTY.EASY },
      { content: 'What is refrigeration?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between refrigeration and air conditioning?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a compressor in a refrigeration system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an evaporator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a condenser?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is preventive maintenance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is predictive maintenance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is corrective maintenance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between preventive and corrective maintenance?', difficulty: DIFFICULTY.HARD },
      { content: 'Why is maintenance important for machines?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is troubleshooting in mechanical systems?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you troubleshoot a machine that suddenly stops working?', difficulty: DIFFICULTY.HARD },
      { content: 'What would you check first if a machine starts making unusual noise?', difficulty: DIFFICULTY.HARD },
      { content: 'What would you check if a rotating machine starts vibrating excessively?', difficulty: DIFFICULTY.HARD },
      { content: 'What is vibration in a mechanical system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is vibration monitoring important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is robotics?', difficulty: DIFFICULTY.EASY },
      { content: 'How are robots used in manufacturing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is automation in manufacturing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between automation and manual manufacturing?', difficulty: DIFFICULTY.HARD },
      { content: 'What is Industry 4.0?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How is IoT used in manufacturing?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a sensor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an actuator?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a sensor and an actuator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is mechatronics?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How is mechatronics related to mechanical engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a mechanical system?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a control system in a mechanical application?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a project you have worked on during your mechanical engineering studies?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What was your role in your mechanical engineering project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What was the most difficult part of your mechanical engineering project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What did you learn from your mechanical engineering project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you approach designing a simple mechanical component?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you choose a material for a mechanical component?', difficulty: DIFFICULTY.HARD },
      { content: 'What factors should be considered when selecting a material for a machine part?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you improve the efficiency of a mechanical system?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you reduce wear in a machine component?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you reduce energy consumption in a mechanical system?', difficulty: DIFFICULTY.HARD },
      { content: 'What safety precautions should be followed while working with machines?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is preventive maintenance important in an industrial machine?', difficulty: DIFFICULTY.MEDIUM },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  [BRANCHES.CIVIL]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'What is civil engineering?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main areas of civil engineering?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a structure?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a building?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a load in civil engineering?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the different types of loads on a structure?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is dead load?', difficulty: DIFFICULTY.EASY },
      { content: 'What is live load?', difficulty: DIFFICULTY.EASY },
      { content: 'What is wind load?', difficulty: DIFFICULTY.EASY },
      { content: 'What is earthquake load?', difficulty: DIFFICULTY.EASY },
      { content: 'What is force?', difficulty: DIFFICULTY.EASY },
      { content: 'What is stress?', difficulty: DIFFICULTY.EASY },
      { content: 'What is strain?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between stress and strain?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is elasticity?', difficulty: DIFFICULTY.EASY },
      { content: 'What is plasticity?', difficulty: DIFFICULTY.EASY },
      { content: 'What is strength of a material?', difficulty: DIFFICULTY.EASY },
      { content: 'What is stiffness?', difficulty: DIFFICULTY.EASY },
      { content: 'What is ductility?', difficulty: DIFFICULTY.EASY },
      { content: 'What is brittleness?', difficulty: DIFFICULTY.EASY },
      { content: 'What is factor of safety?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is concrete?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main ingredients of concrete?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is cement used in concrete?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of water in concrete?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the role of aggregates in concrete?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between fine aggregate and coarse aggregate?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is cement?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the common types of cement?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the water-cement ratio?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is the water-cement ratio important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is workability of concrete?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is curing of concrete?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is curing important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the setting time of cement?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between initial and final setting time?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a concrete mix?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a nominal mix of concrete?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a design mix?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is reinforced cement concrete?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is steel used in reinforced concrete?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is prestressed concrete?', difficulty: DIFFICULTY.HARD },
      { content: 'What is the difference between RCC and prestressed concrete?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a concrete slab?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a beam?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a column?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a footing?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a foundation?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is a foundation important?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the common types of foundations?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between shallow and deep foundations?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a pile foundation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'When is a pile foundation used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a retaining wall?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of a retaining wall?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a staircase?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the common types of staircases?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a lintel?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a plinth?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a roof?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the common types of roofs?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a load-bearing structure?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a framed structure?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a load-bearing structure and a framed structure?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a brick?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the common types of bricks?', difficulty: DIFFICULTY.EASY },
      { content: 'What is mortar?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of mortar in masonry?', difficulty: DIFFICULTY.EASY },
      { content: 'What is brick masonry?', difficulty: DIFFICULTY.EASY },
      { content: 'What is block masonry?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between brick and concrete blocks?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is plastering?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is plastering done?', difficulty: DIFFICULTY.EASY },
      { content: 'What is painting in building construction?', difficulty: DIFFICULTY.EASY },
      { content: 'What is waterproofing?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is waterproofing important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is dampness in a building?', difficulty: DIFFICULTY.EASY },
      { content: 'What causes dampness in buildings?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How can dampness in buildings be prevented?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is building construction?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main stages of building construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is site investigation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is site investigation important before construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is surveying?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is surveying important in civil engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is leveling in surveying?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a benchmark in surveying?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a total station?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is GPS surveying?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between surveying and leveling?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a contour?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a contour map?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is soil?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the basic types of soil?', difficulty: DIFFICULTY.EASY },
      { content: 'What is soil classification?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is bearing capacity of soil?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is bearing capacity important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is soil compaction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is soil compaction done?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is settlement of soil?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What causes settlement?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a retaining structure?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is slope stability?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a slope failure?', difficulty: DIFFICULTY.HARD },
      { content: 'What is geotechnical engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is transportation engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a road?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main layers of a flexible pavement?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a pavement?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between flexible and rigid pavement?', difficulty: DIFFICULTY.HARD },
      { content: 'What is asphalt?', difficulty: DIFFICULTY.EASY },
      { content: 'What is bitumen?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is bitumen used in road construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a highway?', difficulty: DIFFICULTY.EASY },
      { content: 'What is road drainage?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is drainage important for roads?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a traffic signal?', difficulty: DIFFICULTY.EASY },
      { content: 'What is traffic management?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is traffic volume?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a bridge?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main components of a bridge?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a culvert?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a bridge and a culvert?', difficulty: DIFFICULTY.HARD },
      { content: 'What is environmental engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is wastewater?', difficulty: DIFFICULTY.EASY },
      { content: 'What is sewage?', difficulty: DIFFICULTY.EASY },
      { content: 'What is sewage treatment?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is wastewater treatment important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a water treatment plant?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is potable water?', difficulty: DIFFICULTY.EASY },
      { content: 'What is water supply engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are the main sources of water?', difficulty: DIFFICULTY.EASY },
      { content: 'What is groundwater?', difficulty: DIFFICULTY.EASY },
      { content: 'What is surface water?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a water distribution system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a drainage system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is solid waste management?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is solid waste management important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is air pollution?', difficulty: DIFFICULTY.EASY },
      { content: 'What is water pollution?', difficulty: DIFFICULTY.EASY },
      { content: 'What is sustainable construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is green building?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is sustainability important in construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is building information modeling?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is BIM?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How is BIM used in civil engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is AutoCAD?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is AutoCAD used in civil engineering?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is quantity surveying?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a bill of quantities?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is estimation in construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is estimation important in construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a construction schedule?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is project scheduling important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is project management in construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is quality control in construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is quality control important in construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is quality assurance in construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between quality control and quality assurance?', difficulty: DIFFICULTY.HARD },
      { content: 'What is site supervision?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is construction safety?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is safety important at a construction site?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are some common safety hazards at a construction site?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is personal protective equipment?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is PPE important on a construction site?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is scaffolding?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is scaffolding used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is formwork?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is formwork used in concrete construction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is reinforcement in concrete?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is reinforcement provided in concrete structures?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is corrosion of reinforcement?', difficulty: DIFFICULTY.HARD },
      { content: 'How can reinforcement corrosion be prevented?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a crack in a concrete structure?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What can cause cracks in concrete?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you inspect a concrete structure for damage?', difficulty: DIFFICULTY.HARD },
      { content: 'What would you check if a building develops cracks?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you investigate a construction defect?', difficulty: DIFFICULTY.HARD },
      { content: 'What is maintenance of a building?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is building maintenance important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is structural maintenance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a civil engineering project you have worked on during your studies?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What was your role in your civil engineering project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What was the most difficult part of your civil engineering project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What did you learn from your civil engineering project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you choose a suitable material for a construction project?', difficulty: DIFFICULTY.HARD },
      { content: 'What factors should be considered when selecting a foundation?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you improve the quality of a concrete structure?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you reduce water usage on a construction site?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you improve safety at a construction site?', difficulty: DIFFICULTY.HARD },
      { content: 'How would you handle a construction project that is falling behind schedule?', difficulty: DIFFICULTY.HARD },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  [BRANCHES.ELECTRICAL]: {
    [INTERVIEW_TYPES.TECHNICAL]: [
      { content: 'What is electrical engineering?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the main areas of electrical engineering?', difficulty: DIFFICULTY.EASY },
      { content: 'What is voltage?', difficulty: DIFFICULTY.EASY },
      { content: 'What is current?', difficulty: DIFFICULTY.EASY },
      { content: 'What is resistance?', difficulty: DIFFICULTY.EASY },
      { content: 'What is electrical power?', difficulty: DIFFICULTY.EASY },
      { content: 'What is electrical energy?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between power and energy?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Ohm\'s law?', difficulty: DIFFICULTY.EASY },
      { content: 'What is Kirchhoff\'s Current Law?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Kirchhoff\'s Voltage Law?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a conductor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an insulator?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a semiconductor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a conductor, insulator, and semiconductor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a series circuit and a parallel circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is AC?', difficulty: DIFFICULTY.EASY },
      { content: 'What is DC?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between AC and DC?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is frequency?', difficulty: DIFFICULTY.EASY },
      { content: 'What is phase in an AC circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is power factor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is power factor important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is reactive power?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is active power?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is apparent power?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is impedance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between resistance and impedance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is capacitance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is inductance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a capacitor and an inductor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a capacitor used for?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an inductor used for?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a resistor used for?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a transformer?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is a transformer used?', difficulty: DIFFICULTY.EASY },
      { content: 'How does a transformer work?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a step-up and step-down transformer?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why does a transformer work with AC and not ordinary DC?', difficulty: DIFFICULTY.HARD },
      { content: 'What is transformer efficiency?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are the common losses in a transformer?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an electrical generator?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an electric motor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a motor and a generator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is electromagnetic induction?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is Faraday\'s law of electromagnetic induction?', difficulty: DIFFICULTY.HARD },
      { content: 'What is Lenz\'s law?', difficulty: DIFFICULTY.HARD },
      { content: 'What is a magnetic field?', difficulty: DIFFICULTY.EASY },
      { content: 'What is magnetic flux?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an electromagnet?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a relay?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a circuit breaker?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a fuse?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a fuse and a circuit breaker?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why are circuit breakers used in electrical systems?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is earthing?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is earthing important?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is electrical grounding?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between neutral and earth?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a short circuit?', difficulty: DIFFICULTY.EASY },
      { content: 'What causes a short circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an overload in an electrical circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between overload and short circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a battery?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a battery and a cell?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a rechargeable battery?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a solar cell?', difficulty: DIFFICULTY.EASY },
      { content: 'How does a solar panel generate electricity?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an inverter?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between an inverter and a generator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a rectifier?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a diode?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of a diode in an electrical circuit?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an LED?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a transistor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an operational amplifier?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a logic gate?', difficulty: DIFFICULTY.EASY },
      { content: 'What are the basic logic gates?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a microcontroller?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an embedded system?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a sensor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an actuator?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between a sensor and an actuator?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a control system?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between open-loop and closed-loop control?', difficulty: DIFFICULTY.HARD },
      { content: 'What is feedback in a control system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is automation?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a PLC?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a PLC used for?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a PLC and a microcontroller?', difficulty: DIFFICULTY.HARD },
      { content: 'What is industrial automation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a three-phase system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is three-phase power commonly used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between single-phase and three-phase power?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a star connection?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a delta connection?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between star and delta connections?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an induction motor?', difficulty: DIFFICULTY.EASY },
      { content: 'How does an induction motor work?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a synchronous motor and an induction motor?', difficulty: DIFFICULTY.HARD },
      { content: 'What is motor efficiency?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are common types of electric motors?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is motor starting?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is a starter used for an electric motor?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a variable frequency drive?', difficulty: DIFFICULTY.HARD },
      { content: 'Why is a VFD used with motors?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an electrical power system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are the main parts of an electrical power system?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is power generation?', difficulty: DIFFICULTY.EASY },
      { content: 'What is power transmission?', difficulty: DIFFICULTY.EASY },
      { content: 'What is power distribution?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a substation?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the purpose of a substation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is high voltage used for power transmission?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a transmission line?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a distribution line?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a smart grid?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is renewable energy?', difficulty: DIFFICULTY.EASY },
      { content: 'What is solar power generation?', difficulty: DIFFICULTY.EASY },
      { content: 'What is wind power generation?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a circuit diagram?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an electrical schematic?', difficulty: DIFFICULTY.EASY },
      { content: 'What is a PCB?', difficulty: DIFFICULTY.EASY },
      { content: 'Why is a PCB used?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is electrical measurement?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a multimeter?', difficulty: DIFFICULTY.EASY },
      { content: 'What can a multimeter measure?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you safely measure voltage using a multimeter?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an oscilloscope?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an electrical sensor?', difficulty: DIFFICULTY.EASY },
      { content: 'What is preventive maintenance in electrical systems?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is preventive maintenance important for electrical equipment?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would you check first if an electrical motor suddenly stopped working?', difficulty: DIFFICULTY.HARD },
      { content: 'What would you check if an electrical circuit is not working?', difficulty: DIFFICULTY.HARD },
      { content: 'What are common causes of electrical equipment failure?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What safety precautions should be followed while working with electrical equipment?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is electrical insulation?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why is insulation important in electrical systems?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is insulation resistance?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is an electrical load?', difficulty: DIFFICULTY.EASY },
      { content: 'What are common types of electrical loads?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a resistive load?', difficulty: DIFFICULTY.EASY },
      { content: 'What is an inductive load?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is a capacitive load?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is energy efficiency in electrical systems?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How can electrical energy consumption be reduced?', difficulty: DIFFICULTY.HARD },
      { content: 'What is an electrical engineering project you have worked on during your studies?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What was your role in your electrical engineering project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What was the most difficult part of your electrical engineering project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What did you learn from your electrical engineering project?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you troubleshoot a basic electrical circuit that is not working?', difficulty: DIFFICULTY.HARD },
    ],
    [INTERVIEW_TYPES.HR]: [],
    [INTERVIEW_TYPES.APTITUDE]: [],
  },

  GLOBAL: {
    [INTERVIEW_TYPES.HR]: [
      { content: 'Tell me about yourself.', difficulty: DIFFICULTY.EASY },
      { content: 'Can you briefly introduce yourself?', difficulty: DIFFICULTY.EASY },
      { content: 'Tell me about your educational background.', difficulty: DIFFICULTY.EASY },
      { content: 'Why did you choose your current field of study?', difficulty: DIFFICULTY.EASY },
      { content: 'What made you interested in your field?', difficulty: DIFFICULTY.EASY },
      { content: 'What do you enjoy most about your studies?', difficulty: DIFFICULTY.EASY },
      { content: 'What are some skills you have developed during your studies?', difficulty: DIFFICULTY.EASY },
      { content: 'What are your main strengths?', difficulty: DIFFICULTY.EASY },
      { content: 'What is one weakness you are currently trying to improve?', difficulty: DIFFICULTY.EASY },
      { content: 'What is one achievement you are proud of?', difficulty: DIFFICULTY.EASY },
      { content: 'What are you most proud of about yourself?', difficulty: DIFFICULTY.EASY },
      { content: 'What motivates you to do your best?', difficulty: DIFFICULTY.EASY },
      { content: 'What are your career goals?', difficulty: DIFFICULTY.EASY },
      { content: 'Where do you see yourself in the next three to five years?', difficulty: DIFFICULTY.EASY },
      { content: 'Why did you choose this field as a career?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why did you choose to apply for this role? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What interests you about this role? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why do you think you are suitable for this role? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What skills do you think are important for this role? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Which skill are you currently trying to improve for your future career?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you hope to learn from your first job?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What made you interested in working in this field?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why would you like to start your career at a company? [Assume a suitable company in your field.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are you looking for in your first job?', difficulty: DIFFICULTY.EASY },
      { content: 'What do you expect from your first workplace?', difficulty: DIFFICULTY.EASY },
      { content: 'What would make you excited to come to work every day?', difficulty: DIFFICULTY.EASY },
      { content: 'What made you apply for this opportunity? [Assume a suitable entry-level job opportunity.]', difficulty: DIFFICULTY.EASY },
      { content: 'Why should a company consider hiring you as a fresher?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you think you can contribute as a student or fresher?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What attracts you to this kind of job? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you think would be important to learn when starting a new job? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you prepare yourself before starting a new job? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you think would be the biggest challenge when starting your first job?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would you want to learn during your first few weeks at work? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Why would you choose this career path instead of a different one? [Assume a suitable career related to your field of study.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a project you worked on during your studies. [Assume a simple academic project if you do not have a specific project in mind.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about something you learned from a project during your studies. [Assume a simple academic project if needed.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a challenge you faced while working on something during your studies. [Assume a simple academic task or project.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about something you recently learned on your own.', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you usually learn something that you do not understand?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time when you had to learn something quickly.', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you do when you get stuck while working on something?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you manage multiple assignments or deadlines?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you had to work under pressure.', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you balance your studies with other responsibilities?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you worked with other people on a task. [Assume a college assignment or group activity.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you think makes someone a good team member?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Do you prefer working alone or working in a team? Why?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you handle a disagreement with a teammate? [Assume a college or workplace team.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if a teammate was not completing their part of the work? [Assume a college or workplace team.]', difficulty: DIFFICULTY.HARD },
      { content: 'How would you communicate with someone who had a different opinion from yours?', difficulty: DIFFICULTY.HARD },
      { content: 'Tell me about a time you helped someone with their work. [Assume a college assignment or group activity.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time someone helped you with a difficult task. [Assume a college assignment or group activity.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How would you explain a difficult idea to someone who does not understand the topic?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you make sure your ideas are clearly understood by others?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you handle criticism?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you respond when someone points out a mistake in your work?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you received feedback and used it to improve. [Assume a college or academic situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a mistake you made and what you learned from it. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a difficult situation you faced and how you handled it. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you failed at something and what you learned from it. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you had to adapt to a change. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'Tell me about a time you had to make an important decision. [Assume a college or everyday situation.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would you do if you were given a task you had never done before? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were given a difficult task with a short deadline? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were given instructions that you did not completely understand? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were asked to learn something you had never used before? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you discovered a mistake in your work just before a deadline? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if two teammates disagreed about how to solve a problem? [Assume a typical workplace team.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if your manager gave you a deadline that seemed difficult to meet? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if your first attempt at a task did not work? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were not confident about completing an assigned task? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'How would you ask for help when you need it? [Assume a suitable workplace.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would you do if you did not know the answer to a question during an interview?', difficulty: DIFFICULTY.HARD },
      { content: 'How do you prioritize your tasks when you have several things to do?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you make sure you complete your work on time?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What do you do when you lose motivation while working?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you handle stressful situations?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How comfortable are you with asking for help?', difficulty: DIFFICULTY.EASY },
      { content: 'How do you react when plans suddenly change?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How comfortable are you with working with people you have never met before?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you handle working with someone who has a very different working style from yours? [Assume a typical workplace.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you received feedback that you disagreed with? [Assume a workplace situation.]', difficulty: DIFFICULTY.HARD },
      { content: 'How would you respond if your manager asked you to improve an area where you thought you were already doing well? [Assume a workplace situation.]', difficulty: DIFFICULTY.HARD },
      { content: 'What kind of work environment helps you perform your best? [Assume a typical workplace.]', difficulty: DIFFICULTY.EASY },
      { content: 'What kind of manager do you think helps employees perform well? [Assume a typical workplace.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would you expect from your manager when starting a new job? [Assume a suitable entry-level role.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What does professionalism mean to you?', difficulty: DIFFICULTY.EASY },
      { content: 'What does success mean to you?', difficulty: DIFFICULTY.EASY },
      { content: 'How would your classmates describe you?', difficulty: DIFFICULTY.EASY },
      { content: 'What is one quality that makes you different from others?', difficulty: DIFFICULTY.EASY },
      { content: 'What is something about yourself that you would like to improve?', difficulty: DIFFICULTY.EASY },
      { content: 'What is one habit that has helped you become better at something?', difficulty: DIFFICULTY.EASY },
      { content: 'What is something you struggled with but eventually improved?', difficulty: DIFFICULTY.EASY },
      { content: 'What gives you confidence when facing a new challenge?', difficulty: DIFFICULTY.EASY },
      { content: 'What do you do when you feel nervous before an important event?', difficulty: DIFFICULTY.EASY },
      { content: 'What do you think will be the biggest challenge when moving from college to a workplace?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What are you hoping to gain from your first professional experience?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How do you think your education has prepared you for a workplace?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is one thing you wish you had learned earlier?', difficulty: DIFFICULTY.EASY },
      { content: 'How would you react if your first assignment was different from what you expected? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were asked to learn something completely new during your first month at work? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'What would you do if you were given a task without much guidance? [Assume a suitable entry-level job.]', difficulty: DIFFICULTY.HARD },
      { content: 'How would you build good relationships with your teammates? [Assume a typical workplace.]', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What would make you feel that your first job was a successful experience?', difficulty: DIFFICULTY.EASY },
    ],
    [INTERVIEW_TYPES.APTITUDE]: [
      { content: 'What is 20% of 250?', difficulty: DIFFICULTY.EASY },
      { content: 'If a number is increased by 20% and becomes 240, what was the original number?', difficulty: DIFFICULTY.EASY },
      { content: 'A product costs ₹500 and is sold for ₹600. What is the profit percentage?', difficulty: DIFFICULTY.EASY },
      { content: 'A product is bought for ₹800 and sold for ₹720. What is the loss percentage?', difficulty: DIFFICULTY.EASY },
      { content: 'If the price of an item increases from ₹400 to ₹480, what is the percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'If a number is decreased by 25% and becomes 150, what was the original number?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the average of 10, 20, 30, 40, and 50?', difficulty: DIFFICULTY.EASY },
      { content: 'The average of five numbers is 24. What is their total?', difficulty: DIFFICULTY.EASY },
      { content: 'The average age of four people is 25 years. What is their total age?', difficulty: DIFFICULTY.EASY },
      { content: 'The average of three numbers is 30. If two of the numbers are 20 and 40, what is the third number?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'The ratio of two numbers is 2:3 and their sum is 50. What are the two numbers?', difficulty: DIFFICULTY.EASY },
      { content: 'The ratio of boys to girls in a class is 3:2. If there are 30 boys, how many girls are there?', difficulty: DIFFICULTY.EASY },
      { content: 'If 5 pens cost ₹100, how much would 8 pens cost at the same rate?', difficulty: DIFFICULTY.EASY },
      { content: 'A person earns ₹30,000 per month and saves ₹6,000. What percentage of their income do they save?', difficulty: DIFFICULTY.EASY },
      { content: 'If 40% of a number is 80, what is the number?', difficulty: DIFFICULTY.EASY },
      { content: 'What is 15% of 360?', difficulty: DIFFICULTY.EASY },
      { content: 'A number is increased from 200 to 250. What is the percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'A number is reduced from 500 to 400. What is the percentage decrease?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between simple interest and compound interest?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the simple interest on ₹5,000 at 10% per year for 2 years?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the amount after applying 10% simple interest to ₹2,000 for 3 years?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If ₹10,000 is invested at 10% compound interest per year, what will be the amount after one year?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the formula for simple interest?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the formula for calculating profit percentage?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the formula for calculating loss percentage?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the formula for calculating percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'A train travels 120 km in 2 hours. What is its average speed?', difficulty: DIFFICULTY.EASY },
      { content: 'A car travels at 60 km/h for 3 hours. What distance does it cover?', difficulty: DIFFICULTY.EASY },
      { content: 'How much time does it take to travel 150 km at a speed of 50 km/h?', difficulty: DIFFICULTY.EASY },
      { content: 'A person walks at 5 km/h. How long will it take to walk 15 km?', difficulty: DIFFICULTY.EASY },
      { content: 'Two cars travel at speeds of 40 km/h and 60 km/h. Which car covers more distance in 2 hours and by how much?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between speed and velocity?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A train travels 300 km at an average speed of 75 km/h. How long does the journey take?', difficulty: DIFFICULTY.EASY },
      { content: 'If a person\'s speed increases from 40 km/h to 50 km/h, what is the percentage increase in speed?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A man completes a journey in 5 hours at 40 km/h. How far does he travel?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the basic formula relating distance, speed, and time?', difficulty: DIFFICULTY.EASY },
      { content: 'If one person can complete a task in 10 days, what fraction of the work can they complete in one day?', difficulty: DIFFICULTY.EASY },
      { content: 'If one person can complete a job in 10 days and another can complete it in 20 days, how long will they take together?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A can complete a task in 12 days and B can complete it in 18 days. How long will they take working together?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 5 workers complete a job in 12 days, how many worker-days are required?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 10 workers can complete a task in 6 days, how many days would 5 workers need at the same rate?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A pipe can fill a tank in 4 hours. What fraction of the tank does it fill in one hour?', difficulty: DIFFICULTY.EASY },
      { content: 'One pipe fills a tank in 6 hours and another fills it in 3 hours. How long will they take together?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If a person completes half of a task in 5 days, how many days would they need to complete the whole task at the same rate?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between work and rate of work?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of getting a head when a fair coin is tossed?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of getting a 6 when a fair die is rolled?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of getting an even number on a fair die?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of drawing a red card from a standard deck of cards?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of getting two heads when a fair coin is tossed twice?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A bag contains 3 red balls and 2 blue balls. What is the probability of picking a red ball?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between probability and possibility?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the probability of an event that is certain to happen?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the probability of an impossible event?', difficulty: DIFFICULTY.EASY },
      { content: 'If a coin is tossed three times, how many possible outcomes are there?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the next number in the sequence 2, 4, 6, 8, 10?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the next number in the sequence 3, 6, 12, 24?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the next number in the sequence 1, 4, 9, 16, 25?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the missing number in the sequence 5, 10, 15, 20, __?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the missing number in the sequence 2, 6, 12, 20, __?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the next number in the sequence 1, 1, 2, 3, 5, 8?', difficulty: DIFFICULTY.EASY },
      { content: 'If A is taller than B and B is taller than C, who is the shortest?', difficulty: DIFFICULTY.EASY },
      { content: 'If all roses are flowers and some flowers are red, can we conclude that all roses are red?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A clock shows 3:00. What is the angle between the hour and minute hands?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'How many degrees are there in a full circle?', difficulty: DIFFICULTY.EASY },
      { content: 'How many minutes are there in 2.5 hours?', difficulty: DIFFICULTY.EASY },
      { content: 'If today is Monday, what day will it be after 10 days?', difficulty: DIFFICULTY.EASY },
      { content: 'How many days are there in two weeks?', difficulty: DIFFICULTY.EASY },
      { content: 'If a shirt is discounted by 20% from ₹1,000, what is the final price?', difficulty: DIFFICULTY.EASY },
      { content: 'A shop offers two successive discounts of 10% and 20%. Is the total discount 30%?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'An item costs ₹1,000 after a 20% discount. What was its original price?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A salary increases from ₹25,000 to ₹30,000. What is the percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'If your monthly expenses are ₹18,000 and your income is ₹30,000, what percentage of your income is spent?', difficulty: DIFFICULTY.EASY },
      { content: 'A student scores 72 out of 100 in an exam. What percentage did the student score?', difficulty: DIFFICULTY.EASY },
      { content: 'A student scores 80 marks in one test and 90 marks in another. What is the average score?', difficulty: DIFFICULTY.EASY },
      { content: 'If 60% of a class of 50 students are present, how many students are present?', difficulty: DIFFICULTY.EASY },
      { content: 'A company has 200 employees and 25% work remotely. How many employees work remotely?', difficulty: DIFFICULTY.EASY },
      { content: 'If 30% of a number is 45, what is 70% of the same number?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A number is divided in the ratio 4:5. If the smaller part is 20, what is the larger part?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'The ratio of two numbers is 5:7 and their difference is 18. What are the numbers?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 4 notebooks cost ₹120, what is the cost of 10 notebooks?', difficulty: DIFFICULTY.EASY },
      { content: 'If 12 workers produce 240 units in a day, how many units would 6 workers produce at the same rate?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A machine produces 100 units in 5 hours. How many units does it produce per hour?', difficulty: DIFFICULTY.EASY },
      { content: 'A company produced 800 units last month and 1,000 units this month. What is the percentage increase?', difficulty: DIFFICULTY.EASY },
      { content: 'A student spends 2 hours studying, 1 hour exercising, and 3 hours on other activities each day. What percentage of the 6 hours is spent studying?', difficulty: DIFFICULTY.EASY },
      { content: 'A person travels 40 km in the first hour and 60 km in the second hour. What is the average speed for the two-hour journey?', difficulty: DIFFICULTY.EASY },
      { content: 'A car travels half of a journey at 40 km/h and the other half at 60 km/h. Is the average speed 50 km/h?', difficulty: DIFFICULTY.HARD },
      { content: 'A person buys an item for ₹500 and wants a 20% profit. At what price should it be sold?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A product has a marked price of ₹2,000 and is sold for ₹1,600. What percentage discount was given?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 3 machines produce 900 units in 5 hours, how many units can one machine produce in 5 hours at the same rate?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'A tank contains 100 liters of water. If 20 liters are removed, what percentage of the water remains?', difficulty: DIFFICULTY.EASY },
      { content: 'A class has 40 students. If 5 students are absent, what percentage of students are present?', difficulty: DIFFICULTY.EASY },
      { content: 'If a number is multiplied by 5 and then increased by 10, the result is 60. What is the number?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'If 3x = 27, what is the value of x?', difficulty: DIFFICULTY.EASY },
      { content: 'If x + 15 = 40, what is the value of x?', difficulty: DIFFICULTY.EASY },
      { content: 'If 2x + 5 = 25, what is the value of x?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the smallest positive number divisible by both 4 and 6?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the greatest common factor of 12 and 18?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the least common multiple of 6 and 8?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the difference between a prime number and a composite number?', difficulty: DIFFICULTY.EASY },
      { content: 'Is 29 a prime number? Why?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the remainder when 25 is divided by 4?', difficulty: DIFFICULTY.EASY },
      { content: 'A number is divisible by both 3 and 5. What can you say about the number?', difficulty: DIFFICULTY.MEDIUM },
      { content: 'What is the square of 15?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the square root of 144?', difficulty: DIFFICULTY.EASY },
      { content: 'What is 2 to the power of 5?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the value of 10 divided by 0.5?', difficulty: DIFFICULTY.EASY },
      { content: 'What is the difference between an odd number and an even number?', difficulty: DIFFICULTY.EASY },
      { content: 'If five consecutive integers have an average of 20, what is the middle number?', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
};

module.exports = localQuestions;
