INSERT INTO "interview_question_bank" ("interview_type", "branch", "difficulty", "question") VALUES
('TECHNICAL','COMPUTER_SCIENCE','EASY','What is the difference between a stack and a queue?'),
('TECHNICAL','COMPUTER_SCIENCE','EASY','What is recursion? Give a simple example.'),
('TECHNICAL','COMPUTER_SCIENCE','EASY','What is a database index and why is it useful?'),
('TECHNICAL','COMPUTER_SCIENCE','MEDIUM','Explain the difference between processes and threads.'),
('TECHNICAL','COMPUTER_SCIENCE','MEDIUM','What is a hash table and how are collisions handled?'),
('TECHNICAL','COMPUTER_SCIENCE','MEDIUM','Explain the CAP theorem.'),
('TECHNICAL','COMPUTER_SCIENCE','HARD','How would you design a cache for a high-traffic web service?'),
('TECHNICAL','COMPUTER_SCIENCE','HARD','Explain the difference between concurrency and parallelism.'),
('TECHNICAL','COMPUTER_SCIENCE','HARD','What causes a distributed-system deadlock and how can it be prevented?'),
('TECHNICAL','ELECTRONICS','EASY','Explain Ohm''s law and one practical application.'),
('TECHNICAL','ELECTRONICS','EASY','What is the difference between analog and digital signals?'),
('TECHNICAL','ELECTRONICS','EASY','What is a transistor used for?'),
('TECHNICAL','ELECTRONICS','MEDIUM','Compare a BJT and a MOSFET.'),
('TECHNICAL','ELECTRONICS','MEDIUM','What is a flip-flop and where is it used?'),
('TECHNICAL','ELECTRONICS','MEDIUM','Explain the function of an operational amplifier.'),
('TECHNICAL','ELECTRONICS','HARD','How does impedance matching affect signal transfer?'),
('TECHNICAL','ELECTRONICS','HARD','Compare AM and FM modulation.'),
('TECHNICAL','ELECTRONICS','HARD','How would you reduce noise in a mixed-signal circuit?'),
('TECHNICAL','MECHANICAL','EASY','State the first law of thermodynamics.'),
('TECHNICAL','MECHANICAL','EASY','What is stress and strain?'),
('TECHNICAL','MECHANICAL','EASY','What is the purpose of a bearing?'),
('TECHNICAL','MECHANICAL','MEDIUM','Compare forging, casting, and machining.'),
('TECHNICAL','MECHANICAL','MEDIUM','Explain the working principle of a Carnot engine.'),
('TECHNICAL','MECHANICAL','MEDIUM','What is fatigue failure?'),
('TECHNICAL','MECHANICAL','HARD','Explain Bernoulli''s principle in an engineering application.'),
('TECHNICAL','MECHANICAL','HARD','How do laminar and turbulent flow differ?'),
('TECHNICAL','MECHANICAL','HARD','How would you select a material for a high-temperature component?'),
('TECHNICAL','CIVIL','EASY','What are the main types of foundations?'),
('TECHNICAL','CIVIL','EASY','What is the purpose of surveying?'),
('TECHNICAL','CIVIL','EASY','What is the difference between cement and concrete?'),
('TECHNICAL','CIVIL','MEDIUM','Explain soil bearing capacity.'),
('TECHNICAL','CIVIL','MEDIUM','What is the difference between working-stress and limit-state design?'),
('TECHNICAL','CIVIL','MEDIUM','What properties are checked in fresh concrete?'),
('TECHNICAL','CIVIL','HARD','What is prestressed concrete and why is it used?'),
('TECHNICAL','CIVIL','HARD','How would you manage quality control for a concrete pour?'),
('TECHNICAL','CIVIL','HARD','What factors affect a structural load calculation?'),
('TECHNICAL','ELECTRICAL','EASY','State Kirchhoff''s current law.'),
('TECHNICAL','ELECTRICAL','EASY','What is the role of a transformer?'),
('TECHNICAL','ELECTRICAL','EASY','What is electrical power factor?'),
('TECHNICAL','ELECTRICAL','MEDIUM','Compare star and delta connections.'),
('TECHNICAL','ELECTRICAL','MEDIUM','How does a three-phase induction motor work?'),
('TECHNICAL','ELECTRICAL','MEDIUM','What is the purpose of a circuit breaker?'),
('TECHNICAL','ELECTRICAL','HARD','What is load-flow analysis used for?'),
('TECHNICAL','ELECTRICAL','HARD','Explain symmetrical components in power systems.'),
('TECHNICAL','ELECTRICAL','HARD','How would you improve power factor in an industrial installation?'),
('HR',NULL,'EASY','What motivates you at work?'),
('HR',NULL,'EASY','What are your greatest strengths?'),
('HR',NULL,'EASY','Why do you want this role?'),
('HR',NULL,'EASY','How do you organize your work?'),
('HR',NULL,'MEDIUM','Describe a time you handled a difficult deadline.'),
('HR',NULL,'MEDIUM','How do you handle conflict with a coworker?'),
('HR',NULL,'MEDIUM','Tell me about a mistake and what you learned.'),
('HR',NULL,'HARD','Describe a time you influenced a decision without authority.'),
('APTITUDE',NULL,'EASY','If a train travels 360 km in 4 hours, what is its average speed?'),
('APTITUDE',NULL,'EASY','What is the next number: 3, 6, 11, 18, 27, ?'),
('APTITUDE',NULL,'EASY','If the ratio of A to B is 3:5 and their sum is 48, what are their ages?'),
('APTITUDE',NULL,'EASY','What is the probability of getting one head from one coin toss?'),
('APTITUDE',NULL,'MEDIUM','A pipe fills a tank in 12 hours and another empties it in 15 hours. How long together?'),
('APTITUDE',NULL,'MEDIUM','A shopkeeper marks up an item by 40 percent then discounts it by 20 percent. What is the profit percentage?'),
('APTITUDE',NULL,'MEDIUM','What is the probability of at least one head in three coin tosses?'),
('APTITUDE',NULL,'HARD','A boat travels upstream in 5 hours and downstream in 2 hours over the same distance. How would you find current speed?');
